/*
  Copyright (C) 2010, Nuno Subtil

  This file is part of Teppic.

  Teppic is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  Teppic is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with Teppic.  If not, see <http://www.gnu.org/licenses/>.
*/

// SPR register map for 18F2550
enum {
    SPPDATA  = 0xf62,
    SPPCFG,
    SPPEPS,
    SPPCON,
    UFRML,
    UFRMH,
    UIR,
    UIE,
    UEIR,
    UEIE,
    USTAT,
    UCON,
    UADDR,
    UCFG,
    UEP0,
    UEP1,
    UEP2,
    UEP3,
    UEP4,
    UEP5,
    UEP6,
    UEP7,
    UEP8,
    UEP9,
    UEP10,
    UEP11,
    UEP12,
    UEP13,
    UEP14,
    UEP15,
    PORTA,
    PORTB,
    PORTC,
    uimp_f83,
    PORTE,
    uimp_f85,
    uimp_f86,
    uimp_f87,
    uimp_f88,
    LATA,
    LATB,
    LATC,
    uimp_f8c,
    uimp_f8d,
    uimp_f8e,
    uimp_f8f,
    uimp_f90,
    uimp_f91,
    TRISA,
    TRISB,
    TRISC,
    uimp_f95,
    uimp_f96,
    uimp_f97,
    uimp_f98,
    uimp_f99,
    uimp_f9a,
    OSCTUNE,
    uimp_f9c,
    PIE1,
    PIR1,
    IPR1,
    PIE2,
    PIR2,
    IPR2,
    uimp_fa3,
    uimp_fa4,
    uimp_fa5,
    EECON1,
    EECON2,
    EEDATA,
    EEADDR,
    uimp_faa,
    RCSTA,
    TXSTA,
    TXREG,
    RCREG,
    SPBRG,
    SBPRGH,
    T3CON,
    TMR3L,
    TMR3H,
    CMCON,
    CVRCON,
    ECCP1AS,
    ECCP1DEL,
    BAUDCON,
    uimp_fb9,
    CCP2CON,
    CCPR2L,
    CCPR2H,
    CCP1CON,
    CCPR1L,
    CCPR1H,
    ADCON2,
    ADCON1,
    ADCON0,
    ADRESL,
    ADRESH,
    SSPCON2,
    SSPCON1,
    SSPSTAT,
    SSPADD,
    SSPBUF,
    T2CON,
    PR2,
    TMR2,
    T1CON,
    TMR1L,
    TMR1H,
    RCON,
    WDTCON,
    HLVDCON,
    OSCCON,
    uimp_fd4,
    T0CON,
    TMR0L,
    TMR0H,
    STATUS,
    FSR2L,
    FSR2H,
    PLUSW2,
    PREINC2,
    POSTDEC2,
    POSTINC2,
    INDF2,
    BSR,
    FSR1L,
    FSR1H,
    PLUSW1,
    PREINC1,
    POSTDEC1,
    POSTINC1,
    INDF1,
    WREG,
    FSR0L,
    FSR0H,
    PLUSW0,
    PREINC0,
    POSTDEC0,
    POSTINC0,
    INDF0,
    INTCON3,
    INTCON2,
    INTCON,
    PRODL,
    PRODH,
    TABLAT,
    TBLPTRL,
    TBLPTRH,
    TBLPTRU,
    PCL,
    PCLATH,
    PCLATU,
    STKPTR,
    TOSL,
    TOSH,
    TOSU
};
